### ISSUE TITLE
Arp::System::Commons::InvalidConfigException

### ISSUE THREAD

**Issue by OWarneke** [PLCnext/SampleRuntime#1] opened 2019-08-14 12:05 UTC
# Error when starting up a test PLCnextApp

Output.log Content
```
05.08.19 16:41:02.644 ApplicationBase           FATAL   - Fatal error occurs in application 'MainProcess':
05.08.19 16:41:02.645 ApplicationBase           FATAL   - Exception occurs: Exception of type 'Arp::System::Commons::InvalidConfigException' was thrown
Component 'Arp.System.Lm' has an invalid configuration: Process '' is unknown.
  at: Arp::System::Acf::Internal::Sm::SystemManager::LoadConfig()
  at: Arp::System::Acf::Internal::Sm::SystemManager::SetupSystemSettings()
  at: Arp::System::Acf::Internal::Sm::SystemManager::SetupSystem()
  at: Arp::System::Acf::Internal::MainApplicationBase::SetupInternal()
  at: Arp::System::Acf::Internal::ApplicationBase::Setup(Arp::System::Commons::Diagnostics::Logging::LogLevel,charconst*)
  at: Arp::System::Acf::Internal::ApplicationBase::Main(int, char**, Arp::System::Commons::Diagnostics::Logging::LogLevel)
  at: Arp.System.Application(+0x18cbe) [0x47dcbe]
  at: /lib/libc.so.6(__libc_start_main+0x97) [0xb6a6e4a4]

```

What might be the cause of this issue?
The Atribute process is in all config files "<process="PLCNextApp">"
Why is it empty in the error message?

**Comment by OWarneke** [comment] 2019-08-14 12:18
Check in your ".acf.config" file the binary path of your process.
The binary path shal point directly to the executable.
Also make sure the file permissions are sufficient for the plcnext firmware user to execute this file.

WRONG:
`<Process name="PLCNextApp" binaryPath="/root/PLCNext/PLCNextApp/" workingDirectory="/root/PLCNext/PLCNextApp/">`

CORRECT:
`<Process name="PLCNextApp" binaryPath="/root/PLCNext/PLCNextApp/**PLCNextApp**" workingDirectory="/root/PLCNext/PLCNextApp/">`

**Comment by RuneEspeseth** [comment] 2019-08-14 13:40
I get the same error even though the .acf.config has the correct bijnaryPath. What could be the cause ?

**Comment by OWarneke** [comment] 2019-08-14 13:52
@RuneEspeseth Is the error exactly the same or is maybe a different Configuarion Atribute mentioned? Can you attach the config files you are using? Please also check with `ls -la` the permissions on your file system.

**Comment by RuneEspeseth** [comment] 2019-08-16 11:08
I believe my issues above were caused by several errors:

1. The file-names Default.acf.config and Default.acf.setting should be PLCNextApp.acf.config and PLCNextApp.acf.setting
2. The files  PLCNextApp.acf.config and PLCNextApp.acf.setting did not reside in the 'data' sub-directory of the application.
3. PLCNext.acf.config was not copied to ~/projects/Default

**Comment by RuneEspeseth** [comment] 2019-08-16 13:00
I am still having trouble getting everything to run smoothly. The application gets an exception on the code
`ArpSystemModule_Load("/usr/lib", "PLCNextApp", "./data/PLCNextApp.acf.settings");`

It seems the error message in 'Output.log' is 
" Could not read port count for adapter '1' " . What does this mean ?

See the output.log below:
[Output.log](https://github.com/PLCnext/SampleRuntime/files/3509637/Output.log)

This is my file-system:
`admin@axcf2152:/opt/plcnext/PLCNext/PLCNextApp$ ls -la
total 392
drwxr-xr-x 6 admin plcnext   4096 Aug 16 14:19 .
drwxr-xr-x 3 admin plcnext   4096 Aug 14 14:56 ..
-rw-rw-r-- 1 admin plcnext   2764 Aug 16 12:18 Application.xml
drwxrwxr-x 3 admin plcnext   4096 Aug 16 11:19 Components
-rw-rw-r-- 1 admin plcnext   1580 Aug 16 14:24 Messages.log
drwxrwxr-x 2 admin plcnext  73728 Aug 16 12:18 Models
-rwxrwxr-x 1 admin plcnext 297536 Aug 16 11:20 PLCNextApp
drwxrwxr-x 3 admin plcnext   4096 Aug 16 13:20 data
drwxr-xr-x 2 admin plcnext   4096 Aug 16 14:18 lib
`
The 'data' folder only contains PLCNextApp.acf.config and PLCNextApp.acf.settings (I had to append .txt here for file attachment to work... ) :
[PLCNextApp.acf.settings.txt](https://github.com/PLCnext/SampleRuntime/files/3509654/PLCNextApp.acf.settings.txt)
[PLCNextApp.acf.config.txt](https://github.com/PLCnext/SampleRuntime/files/3509656/PLCNextApp.acf.config.txt)

**Comment by OWarneke** [comment] 2019-08-16 13:15
>  The application gets an exception on the code
ArpSystemModule_Load("/usr/lib", "PLCNextApp", "./data/PLCNextApp.acf.settings");

That is because the home directory of the user executing the plcnext application is not at `/opt/plcnext/PLCNext/PLCNextApp`.

Please try going with the full path to your data directory.
`/opt/plcnext/PLCNext/PLCNextApp/data/PLCNextApp.acf.settings`

As to why it is throwing a the strange error code I suspect you might have changed some default config files?

**Comment by martinboers** [comment] 2019-08-16 13:35
Just to be clear on some of the errors mentioned earlier (for those coming after):

> 1. The file-names Default.acf.config and Default.acf.setting should be PLCNextApp.acf.config and PLCNextApp.acf.setting

This statement is not correct. The PLCnext Control comes with default configuration files, including one in the `/opt/plcnext/projects/Default` directory called `Default.acf.config`. This default configuration file should **never** be renamed, moved or deleted - this file, with this name, and with the default contents, is required for the smooth startup of the PLC.

The `.acf.config` file for your own runtime application can be called whatever you want, including `Default.acf.config`, if you want (but of course then it can't be located in the `/opt/plcnext/projects/Default` directory).

Your own `.acf.settings` file can (again) be named whatever you want, including `Default.acf.settings`, so long as this is the filename you pass to `ArpSystemModule_Load`.

> 2. The files  PLCNextApp.acf.config and PLCNextApp.acf.setting did not reside in the 'data' sub-directory of the application.

It makes no difference where these files are located, so long as (a) the location of the `.acf.config` file is referenced in the `/opt/plcnext/projects/Default/Default.acf.settings` file, and (b) the `.acf.settings` filename (including the absolute path) is passed to `ArpSystemModule_Load`.

> 3. PLCNext.acf.config was not copied to ~/projects/Default

OK, missing this step in the tutorial will definitely cause problems.

**Comment by martinboers** [comment] 2019-08-16 13:38
Closing this issue - the remaining problem is being dealt with in issue #2.

**Closed by martinboers** 2019-08-16 13:38 UTC
Labels: question
